spring.datasource.url=${DB_PROD_URL:jdbc:mysql://root:ClsHeoECjFxxJuXydeCEHoxCzrfUzgHS@gondola.proxy.rlwy.net:18323/morago}
spring.datasource.username=${DB_PROD_USER:root}
spring.datasource.password=${DB_PROD_PASS:password}

spring.jpa.hibernate.ddl-auto=update

jwt.issuer=${JWT_ISSUER:morago}
jwt.access-secret=${JWT_ACCESS_SECRET:prod_access_secret}
jwt.refresh-secret=${JWT_REFRESH_SECRET:prod_refresh_secret}
jwt.access-expiration-ms=${JWT_ACCESS_EXPIRATION_MS:900000}
jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}

